/*
 * Font specimen: the same UI text rendered in each candidate font, so the
 * effect of 1-bit quantisation can be judged rather than guessed at.
 *
 * Run with SIM_FONT_SPECIMEN=1. Two families:
 *
 *   fixed_NxM    X11 misc-fixed, a true bitmap font - the u8g2_font_6x13_tf
 *                lineage, and what the UI actually uses. Regular and bold.
 *   mont1_N      Montserrat rasterised directly to 1 bit by lv_font_conv,
 *                which is what the UI used before.
 *
 * Everything here is a diagnostic; none of it is wired into the real pages.
 */
#include "lvgl.h"
#include "ui.h"

/* Generated by tools/make-fonts.sh, Montserrat kept only for this comparison. */
extern const lv_font_t mont1_12;
extern const lv_font_t mont1_14;
extern const lv_font_t mont1_16;
extern const lv_font_t mont1_20;

/* Text that actually appears on the pages, so the comparison is fair. */
static const char *k_sample = "79.70 V  -44.7 A  81.3 %";

static int32_t row(lv_obj_t *parent, const lv_font_t *font, const char *label,
                   int32_t y)
{
    lv_obj_t *tag = lv_label_create(parent);
    lv_obj_set_style_text_font(tag, UI_FONT_S, 0);
    lv_obj_set_style_text_color(tag, lv_color_black(), 0);
    lv_label_set_text(tag, label);
    lv_obj_align(tag, LV_ALIGN_TOP_LEFT, 0, y + (font->line_height - 13) / 2);

    lv_obj_t *l = lv_label_create(parent);
    lv_obj_set_style_text_font(l, font, 0);
    lv_obj_set_style_text_color(l, lv_color_black(), 0);
    lv_label_set_text(l, k_sample);
    lv_obj_align(l, LV_ALIGN_TOP_LEFT, 74, y);

    /* Rows pack against their own line height, so the ladder stays legible
     * however the sizes are later shuffled. */
    return y + font->line_height + 2;
}

void ui_font_specimen(void)
{
    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_white(), 0);
    lv_obj_set_style_pad_all(scr, 4, 0);
    lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

    int32_t y = 0;
    y = row(scr, UI_FONT_S,   "6x13",    y);
    y = row(scr, UI_FONT_S_B, "6x13B",   y);
    y = row(scr, UI_FONT_M,   "7x14",    y);
    y = row(scr, UI_FONT_M_B, "7x14B",   y);
    y = row(scr, UI_FONT_L,   "9x15",    y);
    y = row(scr, UI_FONT_L_B, "9x15B",   y);
    y = row(scr, UI_FONT_XL,  "10x20",   y);
    y = row(scr, UI_FONT_XXL, "6x13B 2x",   y);
    y += 4;
    lv_obj_align(ui_rule(scr), LV_ALIGN_TOP_LEFT, 0, y); y += 5;
    y = row(scr, &mont1_12, "mont 12", y);
    y = row(scr, &mont1_14, "mont 14", y);
    y = row(scr, &mont1_16, "mont 16", y);
    (void)row(scr, &mont1_20, "mont 20", y);
}
