/*******************************************************************************
 * Size: 15 px
 * Bpp: 1
 * Opts: --pcf /tmp/tmp.DHY49teZGH/9x15.pcf --size 15 --name fixed_9x15 --range 0x20-0x7E,0xB0 --symbol-font build/_deps/lvgl-src/scripts/built_in_font/FontAwesome5-Solid+Brands+Regular.woff --symbols 0xF021,0xF071,0xF077,0xF078 --symbol-size 12 --scale 1 -o ui/fonts/fixed_9x15.c
 *
 * Generated by tools/pcf_to_lvgl.py - do not edit by hand.
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef FIXED_9X15
#define FIXED_9X15 1
#endif

#if FIXED_9X15

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 "" */
    0x0,

    /* U+0021 "!" */
    0xfe, 0x60,

    /* U+0022 "" */
    0x99, 0x90,

    /* U+0023 "#" */
    0x49, 0x2f, 0xd2, 0x4b, 0xf4, 0x92,

    /* U+0024 "$" */
    0x10, 0xfa, 0x4c, 0x85, 0x7, 0x5, 0x9, 0x92, 0xf8, 0x40,

    /* U+0025 "%" */
    0x43, 0x4a, 0x92, 0x41, 0x2, 0x9, 0x25, 0x4b, 0x8,

    /* U+0026 "&" */
    0x61, 0x22, 0x44, 0x86, 0xc, 0x65, 0x44, 0x94, 0xc4,

    /* U+0027 "'" */
    0xe0,

    /* U+0028 "(" */
    0x29, 0x49, 0x24, 0x89, 0x10,

    /* U+0029 ")" */
    0x89, 0x12, 0x49, 0x29, 0x40,

    /* U+002A "*" */
    0x11, 0x25, 0x51, 0xc5, 0x52, 0x44, 0x0,

    /* U+002B "+" */
    0x10, 0x20, 0x47, 0xf1, 0x2, 0x4, 0x0,

    /* U+002C "," */
    0xf5, 0x80,

    /* U+002D "-" */
    0xfe,

    /* U+002E "." */
    0xf0,

    /* U+002F "/" */
    0x2, 0x8, 0x10, 0x41, 0x2, 0x8, 0x20, 0x41, 0x0,

    /* U+0030 "0" */
    0x38, 0x8a, 0xc, 0x18, 0x30, 0x60, 0xc1, 0x44, 0x70,

    /* U+0031 "1" */
    0x10, 0x61, 0x44, 0x81, 0x2, 0x4, 0x8, 0x11, 0xfc,

    /* U+0032 "2" */
    0x7d, 0x6, 0x8, 0x20, 0x82, 0x8, 0x20, 0x81, 0xfc,

    /* U+0033 "3" */
    0xfe, 0x4, 0x10, 0x41, 0xc0, 0x40, 0x81, 0x82, 0xf8,

    /* U+0034 "4" */
    0x4, 0x18, 0x51, 0x24, 0x50, 0xbf, 0x82, 0x4, 0x8,

    /* U+0035 "5" */
    0xff, 0x2, 0x5, 0xec, 0x20, 0x40, 0x81, 0x82, 0xf8,

    /* U+0036 "6" */
    0x3c, 0x82, 0x4, 0xb, 0xd8, 0x60, 0xc1, 0x82, 0xf8,

    /* U+0037 "7" */
    0xfe, 0x4, 0x10, 0x20, 0x81, 0x4, 0x8, 0x20, 0x40,

    /* U+0038 "8" */
    0x38, 0x8a, 0xa, 0x23, 0x88, 0xa0, 0xc1, 0x44, 0x70,

    /* U+0039 "9" */
    0x7d, 0x6, 0xc, 0x18, 0x6f, 0x40, 0x81, 0x4, 0xf0,

    /* U+003A ":" */
    0xf0, 0x3c,

    /* U+003B ";" */
    0xf0, 0x3d, 0x60,

    /* U+003C "<" */
    0x8, 0x88, 0x88, 0x41, 0x4, 0x10, 0x40,

    /* U+003D "=" */
    0xfe, 0x0, 0x7, 0xf0,

    /* U+003E ">" */
    0x82, 0x8, 0x20, 0x84, 0x44, 0x44, 0x0,

    /* U+003F "?" */
    0x7d, 0x6, 0x8, 0x10, 0x41, 0x4, 0x8, 0x0, 0x20,

    /* U+0040 "@" */
    0x7d, 0x6, 0xc, 0xfa, 0x34, 0xe6, 0xc0, 0x80, 0xf8,

    /* U+0041 "A" */
    0x10, 0x51, 0x14, 0x18, 0x30, 0x7f, 0xc1, 0x83, 0x4,

    /* U+0042 "B" */
    0xf9, 0xa, 0xc, 0x2f, 0x90, 0xa0, 0xc1, 0x85, 0xf0,

    /* U+0043 "C" */
    0x7d, 0x6, 0x4, 0x8, 0x10, 0x20, 0x40, 0x82, 0xf8,

    /* U+0044 "D" */
    0xf9, 0xa, 0xc, 0x18, 0x30, 0x60, 0xc1, 0x85, 0xf0,

    /* U+0045 "E" */
    0xff, 0x2, 0x4, 0xf, 0x90, 0x20, 0x40, 0x81, 0xfc,

    /* U+0046 "F" */
    0xff, 0x2, 0x4, 0xf, 0x90, 0x20, 0x40, 0x81, 0x0,

    /* U+0047 "G" */
    0x7d, 0x6, 0x4, 0x8, 0x11, 0xe0, 0xc1, 0x82, 0xf8,

    /* U+0048 "H" */
    0x83, 0x6, 0xc, 0x1f, 0xf0, 0x60, 0xc1, 0x83, 0x4,

    /* U+0049 "I" */
    0xf9, 0x8, 0x42, 0x10, 0x84, 0x27, 0xc0,

    /* U+004A "J" */
    0x1f, 0x4, 0x4, 0x4, 0x4, 0x4, 0x4, 0x4, 0x84, 0x78,

    /* U+004B "K" */
    0x83, 0xa, 0x24, 0x8e, 0x14, 0x24, 0x44, 0x85, 0x4,

    /* U+004C "L" */
    0x81, 0x2, 0x4, 0x8, 0x10, 0x20, 0x40, 0x81, 0xfc,

    /* U+004D "M" */
    0x83, 0x7, 0x1d, 0x5a, 0xb2, 0x64, 0xc1, 0x83, 0x4,

    /* U+004E "N" */
    0x83, 0x7, 0xd, 0x19, 0x31, 0x61, 0xc1, 0x83, 0x4,

    /* U+004F "O" */
    0x7d, 0x6, 0xc, 0x18, 0x30, 0x60, 0xc1, 0x82, 0xf8,

    /* U+0050 "P" */
    0xfd, 0x6, 0xc, 0x1f, 0xd0, 0x20, 0x40, 0x81, 0x0,

    /* U+0051 "Q" */
    0x7d, 0x6, 0xc, 0x18, 0x30, 0x60, 0xd1, 0x92, 0xf8, 0x20, 0x30,

    /* U+0052 "R" */
    0xfd, 0x6, 0xc, 0x1f, 0xd2, 0x22, 0x42, 0x83, 0x4,

    /* U+0053 "S" */
    0x7d, 0x6, 0xc, 0x7, 0x1, 0x80, 0xc1, 0x82, 0xf8,

    /* U+0054 "T" */
    0xfe, 0x20, 0x40, 0x81, 0x2, 0x4, 0x8, 0x10, 0x20,

    /* U+0055 "U" */
    0x83, 0x6, 0xc, 0x18, 0x30, 0x60, 0xc1, 0x82, 0xf8,

    /* U+0056 "V" */
    0x83, 0x6, 0xa, 0x24, 0x48, 0x8a, 0x14, 0x28, 0x20,

    /* U+0057 "W" */
    0x83, 0x6, 0xc, 0x19, 0x32, 0x64, 0xc9, 0xaa, 0x88,

    /* U+0058 "X" */
    0x83, 0x5, 0x11, 0x41, 0x2, 0xa, 0x22, 0x83, 0x4,

    /* U+0059 "Y" */
    0x83, 0x5, 0x11, 0x41, 0x2, 0x4, 0x8, 0x10, 0x20,

    /* U+005A "Z" */
    0xfe, 0x4, 0x10, 0x41, 0x4, 0x10, 0x40, 0x81, 0xfc,

    /* U+005B "[" */
    0xf8, 0x88, 0x88, 0x88, 0x88, 0x8f,

    /* U+005C "" */
    0x80, 0x81, 0x1, 0x1, 0x2, 0x2, 0x2, 0x4, 0x4,

    /* U+005D "]" */
    0xf1, 0x11, 0x11, 0x11, 0x11, 0x1f,

    /* U+005E "^" */
    0x10, 0x51, 0x14, 0x10,

    /* U+005F "_" */
    0xff,

    /* U+0060 "`" */
    0x88, 0x80,

    /* U+0061 "a" */
    0x7c, 0x4, 0xb, 0xf8, 0x30, 0xde, 0x80,

    /* U+0062 "b" */
    0x81, 0x2, 0x5, 0xec, 0x30, 0x60, 0xc1, 0xc3, 0x78,

    /* U+0063 "c" */
    0x7d, 0x6, 0x4, 0x8, 0x10, 0x5f, 0x0,

    /* U+0064 "d" */
    0x2, 0x4, 0xb, 0xd8, 0x70, 0x60, 0xc1, 0x86, 0xf4,

    /* U+0065 "e" */
    0x7d, 0x6, 0xf, 0xf8, 0x10, 0x1f, 0x0,

    /* U+0066 "f" */
    0x1c, 0x44, 0x89, 0x2, 0x1f, 0x8, 0x10, 0x20, 0x40,

    /* U+0067 "g" */
    0x7b, 0xa, 0x14, 0x27, 0x90, 0x1f, 0x41, 0x82, 0xf8,

    /* U+0068 "h" */
    0x81, 0x2, 0x5, 0xec, 0x30, 0x60, 0xc1, 0x83, 0x4,

    /* U+0069 "i" */
    0x60, 0x1, 0xc2, 0x10, 0x84, 0x27, 0xc0,

    /* U+006A "j" */
    0xc, 0x0, 0x7, 0x4, 0x10, 0x41, 0x6, 0x18, 0x61, 0x78,

    /* U+006B "k" */
    0x81, 0x2, 0x4, 0x18, 0xd6, 0x30, 0x58, 0x8d, 0x4,

    /* U+006C "l" */
    0xe1, 0x8, 0x42, 0x10, 0x84, 0x27, 0xc0,

    /* U+006D "m" */
    0xed, 0x26, 0x4c, 0x99, 0x32, 0x60, 0x80,

    /* U+006E "n" */
    0xbd, 0x86, 0xc, 0x18, 0x30, 0x60, 0x80,

    /* U+006F "o" */
    0x7d, 0x6, 0xc, 0x18, 0x30, 0x5f, 0x0,

    /* U+0070 "p" */
    0xbd, 0x86, 0xc, 0x18, 0x38, 0x6f, 0x40, 0x81, 0x0,

    /* U+0071 "q" */
    0x7b, 0xe, 0xc, 0x18, 0x30, 0xde, 0x81, 0x2, 0x4,

    /* U+0072 "r" */
    0x9c, 0xc5, 0xa, 0x4, 0x8, 0x10, 0x0,

    /* U+0073 "s" */
    0x7d, 0x6, 0x3, 0xe0, 0x30, 0x5f, 0x0,

    /* U+0074 "t" */
    0x20, 0x43, 0xf1, 0x2, 0x4, 0x8, 0x11, 0x1c,

    /* U+0075 "u" */
    0x85, 0xa, 0x14, 0x28, 0x50, 0x9e, 0x80,

    /* U+0076 "v" */
    0x83, 0x5, 0x12, 0x22, 0x85, 0x4, 0x0,

    /* U+0077 "w" */
    0x83, 0x6, 0x4c, 0x99, 0x35, 0x51, 0x0,

    /* U+0078 "x" */
    0x82, 0x88, 0xa0, 0x82, 0x88, 0xa0, 0x80,

    /* U+0079 "y" */
    0x86, 0x18, 0x61, 0x86, 0x37, 0x41, 0x85, 0xe0,

    /* U+007A "z" */
    0xfe, 0x8, 0x20, 0x82, 0x8, 0x3f, 0x80,

    /* U+007B "{" */
    0x3a, 0x10, 0x82, 0x63, 0x4, 0x42, 0x10, 0x70,

    /* U+007C "|" */
    0xff, 0xf0,

    /* U+007D "}" */
    0xe0, 0x84, 0x22, 0xc, 0x64, 0x10, 0x85, 0xc0,

    /* U+007E "~" */
    0x63, 0x26, 0x30,

    /* U+00B0 "" */
    0x69, 0x96,

    /* U+F021 "" */
    0x0, 0x10, 0xf3, 0x3f, 0xf7, 0x7, 0x61, 0xf4, 0x1f, 0x0, 0xf, 0x82,
    0xf8, 0x6e, 0xe, 0xff, 0xcc, 0xf0, 0x80, 0x0,

    /* U+F071 "" */
    0x3, 0x0, 0x38, 0x1, 0xe0, 0x1f, 0x81, 0xcc, 0xe, 0x70, 0xf3, 0x87,
    0xfe, 0x7c, 0xff, 0xe7, 0xff, 0xfe, 0xff, 0xe0,

    /* U+F077 "" */
    0xc, 0x7, 0x83, 0x31, 0x86, 0xc0, 0xc0,

    /* U+F078 "" */
    0xc0, 0xd8, 0x63, 0x30, 0x78, 0xc, 0x0,

};


/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 144, .box_w = 1, .box_h = 1, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1, .adv_w = 144, .box_w = 1, .box_h = 11, .ofs_x = 4, .ofs_y = 0},
    {.bitmap_index = 3, .adv_w = 144, .box_w = 4, .box_h = 3, .ofs_x = 3, .ofs_y = 7},
    {.bitmap_index = 5, .adv_w = 144, .box_w = 6, .box_h = 8, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 11, .adv_w = 144, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 21, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 30, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 39, .adv_w = 144, .box_w = 1, .box_h = 3, .ofs_x = 4, .ofs_y = 7},
    {.bitmap_index = 40, .adv_w = 144, .box_w = 3, .box_h = 12, .ofs_x = 3, .ofs_y = -1},
    {.bitmap_index = 45, .adv_w = 144, .box_w = 3, .box_h = 12, .ofs_x = 3, .ofs_y = -1},
    {.bitmap_index = 50, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 57, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 64, .adv_w = 144, .box_w = 2, .box_h = 5, .ofs_x = 4, .ofs_y = -3},
    {.bitmap_index = 66, .adv_w = 144, .box_w = 7, .box_h = 1, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 67, .adv_w = 144, .box_w = 2, .box_h = 2, .ofs_x = 4, .ofs_y = 0},
    {.bitmap_index = 68, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 77, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 86, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 95, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 104, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 113, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 122, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 131, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 140, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 149, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 158, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 167, .adv_w = 144, .box_w = 2, .box_h = 7, .ofs_x = 4, .ofs_y = 0},
    {.bitmap_index = 169, .adv_w = 144, .box_w = 2, .box_h = 10, .ofs_x = 4, .ofs_y = -3},
    {.bitmap_index = 172, .adv_w = 144, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 179, .adv_w = 144, .box_w = 7, .box_h = 4, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 183, .adv_w = 144, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 190, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 199, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 208, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 217, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 226, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 235, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 244, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 253, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 262, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 271, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 280, .adv_w = 144, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 287, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 297, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 306, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 315, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 324, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 333, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 342, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 351, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 362, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 371, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 380, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 389, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 398, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 407, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 416, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 425, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 434, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 443, .adv_w = 144, .box_w = 4, .box_h = 12, .ofs_x = 3, .ofs_y = -1},
    {.bitmap_index = 449, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 458, .adv_w = 144, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 464, .adv_w = 144, .box_w = 7, .box_h = 4, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 468, .adv_w = 144, .box_w = 8, .box_h = 1, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 469, .adv_w = 144, .box_w = 3, .box_h = 3, .ofs_x = 3, .ofs_y = 8},
    {.bitmap_index = 471, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 478, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 487, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 494, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 503, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 510, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 519, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 528, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 537, .adv_w = 144, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 544, .adv_w = 144, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 554, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 563, .adv_w = 144, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 570, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 577, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 584, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 591, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 600, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 609, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 616, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 623, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 631, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 638, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 645, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 652, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 659, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 667, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 674, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 3, .ofs_y = -1},
    {.bitmap_index = 682, .adv_w = 144, .box_w = 1, .box_h = 12, .ofs_x = 4, .ofs_y = -1},
    {.bitmap_index = 684, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 692, .adv_w = 144, .box_w = 7, .box_h = 3, .ofs_x = 1, .ofs_y = 7},
    {.bitmap_index = 695, .adv_w = 144, .box_w = 4, .box_h = 4, .ofs_x = 3, .ofs_y = 6},
    {.bitmap_index = 697, .adv_w = 208, .box_w = 12, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 717, .adv_w = 224, .box_w = 13, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 737, .adv_w = 176, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 744, .adv_w = 176, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
};


/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_1[] = {
    0x0, 0xef71, 0xefc1, 0xefc7, 0xefc8
};

/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 176, .range_length = 61385, .glyph_id_start = 96,
        .unicode_list = unicode_list_1, .glyph_id_ofs_list = NULL, .list_length = 5, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};


/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};


/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t fixed_9x15 = {
#else
lv_font_t fixed_9x15 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 15,          /*The maximum line height required by the font*/
    .base_line = 3,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};



#endif /*#if FIXED_9X15*/
