/*******************************************************************************
 * Size: 15 px
 * Bpp: 1
 * Opts: --pcf /tmp/tmp.DHY49teZGH/9x15B.pcf --size 15 --name fixed_9x15b --range 0x20-0x7E,0xB0 --symbol-font build/_deps/lvgl-src/scripts/built_in_font/FontAwesome5-Solid+Brands+Regular.woff --symbols 0xF021,0xF071,0xF077,0xF078 --symbol-size 12 --scale 1 -o ui/fonts/fixed_9x15b.c
 *
 * Generated by tools/pcf_to_lvgl.py - do not edit by hand.
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef FIXED_9X15B
#define FIXED_9X15B 1
#endif

#if FIXED_9X15B

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 "" */
    0x0,

    /* U+0021 "!" */
    0xff, 0xff, 0x30,

    /* U+0022 "" */
    0xde, 0xf6,

    /* U+0023 "#" */
    0x6c, 0xdb, 0xfb, 0x66, 0xdf, 0xdb, 0x36,

    /* U+0024 "$" */
    0x10, 0xfb, 0x5e, 0x8f, 0xf, 0x87, 0x8b, 0xd6, 0xf8, 0x40,

    /* U+0025 "%" */
    0x43, 0xe6, 0xe6, 0x4c, 0x18, 0x18, 0x32, 0x67, 0x67, 0xc2,

    /* U+0026 "&" */
    0x38, 0x6c, 0x6c, 0x78, 0x30, 0x79, 0xcf, 0xc6, 0xce, 0x7b,

    /* U+0027 "'" */
    0xff,

    /* U+0028 "(" */
    0x19, 0x98, 0xcc, 0x63, 0x18, 0x63, 0xc, 0x30,

    /* U+0029 ")" */
    0xc3, 0xc, 0x61, 0x8c, 0x63, 0x31, 0x99, 0x80,

    /* U+002A "*" */
    0x6c, 0x73, 0xf9, 0xc6, 0xc0,

    /* U+002B "+" */
    0x18, 0x18, 0x18, 0xff, 0x18, 0x18, 0x18,

    /* U+002C "," */
    0xfd, 0xbc,

    /* U+002D "-" */
    0xff,

    /* U+002E "." */
    0x6f, 0x60,

    /* U+002F "/" */
    0x3, 0x6, 0x6, 0xc, 0x18, 0x18, 0x30, 0x60, 0x60, 0xc0,

    /* U+0030 "0" */
    0x18, 0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0xc3, 0x66, 0x3c, 0x18,

    /* U+0031 "1" */
    0x31, 0xcf, 0xc, 0x30, 0xc3, 0xc, 0x33, 0xf0,

    /* U+0032 "2" */
    0x3c, 0x66, 0xc3, 0x3, 0x6, 0xc, 0x18, 0x30, 0x60, 0xff,

    /* U+0033 "3" */
    0x7c, 0xc6, 0x3, 0x6, 0x1c, 0x6, 0x3, 0x3, 0xc6, 0x7c,

    /* U+0034 "4" */
    0x6, 0xe, 0x1e, 0x36, 0x66, 0xc6, 0xff, 0x6, 0x6, 0x6,

    /* U+0035 "5" */
    0xfe, 0xc0, 0xc0, 0xdc, 0xe6, 0x3, 0x3, 0xc3, 0x66, 0x3c,

    /* U+0036 "6" */
    0x3c, 0x66, 0xc2, 0xc0, 0xdc, 0xe6, 0xc3, 0xc3, 0x66, 0x3c,

    /* U+0037 "7" */
    0xff, 0x3, 0x3, 0x6, 0xc, 0xc, 0x18, 0x18, 0x18, 0x18,

    /* U+0038 "8" */
    0x3c, 0x66, 0xc3, 0x66, 0x3c, 0x66, 0xc3, 0xc3, 0x66, 0x3c,

    /* U+0039 "9" */
    0x3c, 0x66, 0xc3, 0xc3, 0x67, 0x3b, 0x3, 0x43, 0x66, 0x3c,

    /* U+003A ":" */
    0x6f, 0x60, 0x6, 0xf6,

    /* U+003B ";" */
    0x6f, 0x60, 0x7, 0x73, 0x36,

    /* U+003C "<" */
    0xc, 0x63, 0x18, 0xc3, 0x6, 0xc, 0x18, 0x30,

    /* U+003D "=" */
    0xff, 0x0, 0x0, 0xff,

    /* U+003E ">" */
    0xc1, 0x83, 0x6, 0xc, 0x31, 0x8c, 0x63, 0x0,

    /* U+003F "?" */
    0x7d, 0x8f, 0x18, 0x30, 0xc3, 0xc, 0x0, 0x30, 0x60,

    /* U+0040 "@" */
    0x3c, 0x66, 0xc3, 0xcf, 0xdb, 0xdb, 0xce, 0xc0, 0x63, 0x3e,

    /* U+0041 "A" */
    0x18, 0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0xff, 0xc3, 0xc3, 0xc3,

    /* U+0042 "B" */
    0xfc, 0xc6, 0xc3, 0xc6, 0xfc, 0xc6, 0xc3, 0xc3, 0xc6, 0xfc,

    /* U+0043 "C" */
    0x3e, 0x63, 0xc1, 0xc0, 0xc0, 0xc0, 0xc0, 0xc1, 0x63, 0x3e,

    /* U+0044 "D" */
    0xfc, 0xc6, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc6, 0xfc,

    /* U+0045 "E" */
    0xff, 0x83, 0x6, 0xf, 0xd8, 0x30, 0x60, 0xc1, 0xfc,

    /* U+0046 "F" */
    0xff, 0xc0, 0xc0, 0xc0, 0xfc, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0,

    /* U+0047 "G" */
    0x3e, 0x63, 0xc0, 0xc0, 0xc0, 0xc7, 0xc3, 0xc3, 0x63, 0x3e,

    /* U+0048 "H" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xff, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,

    /* U+0049 "I" */
    0xfc, 0xc3, 0xc, 0x30, 0xc3, 0xc, 0x33, 0xf0,

    /* U+004A "J" */
    0x3c, 0x30, 0xc3, 0xc, 0x30, 0xe3, 0xd9, 0xc0,

    /* U+004B "K" */
    0xc3, 0xc6, 0xcc, 0xd8, 0xf0, 0xf0, 0xd8, 0xcc, 0xc6, 0xc3,

    /* U+004C "L" */
    0xc1, 0x83, 0x6, 0xc, 0x18, 0x30, 0x60, 0xc1, 0xfc,

    /* U+004D "M" */
    0xc3, 0xe7, 0xff, 0xdb, 0xdb, 0xdb, 0xc3, 0xc3, 0xc3, 0xc3,

    /* U+004E "N" */
    0xc3, 0xe3, 0xf3, 0xf3, 0xdb, 0xdb, 0xcf, 0xc7, 0xc7, 0xc3,

    /* U+004F "O" */
    0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x66, 0x3c,

    /* U+0050 "P" */
    0xfe, 0xc3, 0xc3, 0xc3, 0xfe, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0,

    /* U+0051 "Q" */
    0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0xc3, 0xdb, 0xcf, 0x66, 0x3d,

    /* U+0052 "R" */
    0xfe, 0xc3, 0xc3, 0xc3, 0xfe, 0xf8, 0xcc, 0xc6, 0xc3, 0xc3,

    /* U+0053 "S" */
    0x7e, 0xc3, 0xc0, 0xc0, 0x7e, 0x3, 0x3, 0x3, 0xc3, 0x7e,

    /* U+0054 "T" */
    0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,

    /* U+0055 "U" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x66, 0x3c,

    /* U+0056 "V" */
    0xc3, 0xc3, 0xc3, 0x66, 0x66, 0x66, 0x3c, 0x3c, 0x18, 0x18,

    /* U+0057 "W" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xdb, 0xdb, 0xdb, 0xff, 0xe7, 0xc3,

    /* U+0058 "X" */
    0xc3, 0xc3, 0x66, 0x3c, 0x18, 0x18, 0x3c, 0x66, 0xc3, 0xc3,

    /* U+0059 "Y" */
    0xc3, 0xc3, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,

    /* U+005A "Z" */
    0xfe, 0xc, 0x18, 0x61, 0x86, 0x18, 0x60, 0xc1, 0xfc,

    /* U+005B "[" */
    0xfe, 0x31, 0x8c, 0x63, 0x18, 0xc6, 0x31, 0xf0,

    /* U+005C "" */
    0xc0, 0x60, 0x60, 0x30, 0x18, 0x18, 0xc, 0x6, 0x6, 0x3,

    /* U+005D "]" */
    0xf8, 0xc6, 0x31, 0x8c, 0x63, 0x18, 0xc7, 0xf0,

    /* U+005E "^" */
    0x31, 0xec, 0xe1,

    /* U+005F "_" */
    0xff,

    /* U+0060 "`" */
    0xc6, 0x30,

    /* U+0061 "a" */
    0x3e, 0x63, 0x3, 0x7f, 0xc3, 0xc7, 0x7b,

    /* U+0062 "b" */
    0xc0, 0xc0, 0xc0, 0xdc, 0xe6, 0xc3, 0xc3, 0xc3, 0xe6, 0xdc,

    /* U+0063 "c" */
    0x3e, 0x63, 0xc0, 0xc0, 0xc0, 0x63, 0x3e,

    /* U+0064 "d" */
    0x3, 0x3, 0x3, 0x3b, 0x67, 0xc3, 0xc3, 0xc3, 0x67, 0x3b,

    /* U+0065 "e" */
    0x3c, 0x66, 0xc3, 0xff, 0xc0, 0x63, 0x3e,

    /* U+0066 "f" */
    0x1e, 0x33, 0x33, 0x30, 0x30, 0xfc, 0x30, 0x30, 0x30, 0x30,

    /* U+0067 "g" */
    0x7d, 0xc7, 0xc6, 0xc6, 0x7c, 0xc0, 0x7e, 0xc3, 0xc3, 0x7e,

    /* U+0068 "h" */
    0xc0, 0xc0, 0xc0, 0xdc, 0xe6, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,

    /* U+0069 "i" */
    0x30, 0xc0, 0x1c, 0x30, 0xc3, 0xc, 0x33, 0xf0,

    /* U+006A "j" */
    0x6, 0xc, 0x0, 0xf0, 0x60, 0xc1, 0x83, 0x7, 0x8f, 0x1e, 0x37, 0xc0,

    /* U+006B "k" */
    0xc1, 0x83, 0x6, 0x6d, 0x9e, 0x3c, 0x6c, 0xcd, 0x8c,

    /* U+006C "l" */
    0x70, 0xc3, 0xc, 0x30, 0xc3, 0xc, 0x33, 0xf0,

    /* U+006D "m" */
    0xb6, 0xdb, 0xdb, 0xdb, 0xdb, 0xdb, 0xdb,

    /* U+006E "n" */
    0xdc, 0xe6, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,

    /* U+006F "o" */
    0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0x66, 0x3c,

    /* U+0070 "p" */
    0xdc, 0xe6, 0xc3, 0xc3, 0xc3, 0xe6, 0xdc, 0xc0, 0xc0, 0xc0,

    /* U+0071 "q" */
    0x3b, 0x67, 0xc3, 0xc3, 0xc3, 0x67, 0x3b, 0x3, 0x3, 0x3,

    /* U+0072 "r" */
    0xde, 0x73, 0x60, 0x60, 0x60, 0x60, 0x60,

    /* U+0073 "s" */
    0x7e, 0xc3, 0xc0, 0x7e, 0x3, 0xc3, 0x7e,

    /* U+0074 "t" */
    0x30, 0x30, 0xfc, 0x30, 0x30, 0x30, 0x30, 0x33, 0x1e,

    /* U+0075 "u" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x67, 0x3b,

    /* U+0076 "v" */
    0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x3c, 0x18,

    /* U+0077 "w" */
    0xc3, 0xc3, 0xdb, 0xdb, 0xdb, 0xff, 0x66,

    /* U+0078 "x" */
    0xc3, 0x66, 0x3c, 0x18, 0x3c, 0x66, 0xc3,

    /* U+0079 "y" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x67, 0x3b, 0x3, 0xc6, 0x7c,

    /* U+007A "z" */
    0xfc, 0x31, 0x8c, 0x63, 0xf, 0xc0,

    /* U+007B "{" */
    0x3b, 0x18, 0xc6, 0x63, 0xc, 0x63, 0x18, 0x70,

    /* U+007C "|" */
    0xff, 0xff, 0xf0,

    /* U+007D "}" */
    0xe1, 0x8c, 0x63, 0xc, 0x66, 0x31, 0x8d, 0xc0,

    /* U+007E "~" */
    0x73, 0xdb, 0xce,

    /* U+00B0 "" */
    0x7b, 0x3c, 0xde,

    /* U+F021 "" */
    0x0, 0x10, 0xf3, 0x3f, 0xf7, 0x7, 0x61, 0xf4, 0x1f, 0x0, 0xf, 0x82,
    0xf8, 0x6e, 0xe, 0xff, 0xcc, 0xf0, 0x80, 0x0,

    /* U+F071 "" */
    0x3, 0x0, 0x38, 0x1, 0xe0, 0x1f, 0x81, 0xcc, 0xe, 0x70, 0xf3, 0x87,
    0xfe, 0x7c, 0xff, 0xe7, 0xff, 0xfe, 0xff, 0xe0,

    /* U+F077 "" */
    0xc, 0x7, 0x83, 0x31, 0x86, 0xc0, 0xc0,

    /* U+F078 "" */
    0xc0, 0xd8, 0x63, 0x30, 0x78, 0xc, 0x0,

};


/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 144, .box_w = 1, .box_h = 1, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1, .adv_w = 144, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 4, .adv_w = 144, .box_w = 5, .box_h = 3, .ofs_x = 2, .ofs_y = 7},
    {.bitmap_index = 6, .adv_w = 144, .box_w = 7, .box_h = 8, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 13, .adv_w = 144, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 23, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 33, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 43, .adv_w = 144, .box_w = 2, .box_h = 4, .ofs_x = 3, .ofs_y = 6},
    {.bitmap_index = 44, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 52, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 60, .adv_w = 144, .box_w = 7, .box_h = 5, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 65, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 72, .adv_w = 144, .box_w = 3, .box_h = 5, .ofs_x = 3, .ofs_y = -3},
    {.bitmap_index = 74, .adv_w = 144, .box_w = 8, .box_h = 1, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 75, .adv_w = 144, .box_w = 4, .box_h = 3, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 77, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 87, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 97, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 105, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 115, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 125, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 135, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 145, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 155, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 165, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 175, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 185, .adv_w = 144, .box_w = 4, .box_h = 8, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 189, .adv_w = 144, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 194, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 202, .adv_w = 144, .box_w = 8, .box_h = 4, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 206, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 214, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 223, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 233, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 243, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 253, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 263, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 273, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 282, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 292, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 302, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 312, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 320, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 328, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 338, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 347, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 357, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 367, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 377, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 387, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 397, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 407, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 417, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 427, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 437, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 447, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 457, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 467, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 477, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 486, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 494, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 504, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 512, .adv_w = 144, .box_w = 6, .box_h = 4, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 515, .adv_w = 144, .box_w = 8, .box_h = 1, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 516, .adv_w = 144, .box_w = 4, .box_h = 3, .ofs_x = 2, .ofs_y = 8},
    {.bitmap_index = 518, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 525, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 535, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 542, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 552, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 559, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 569, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 579, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 589, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 597, .adv_w = 144, .box_w = 7, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 609, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 618, .adv_w = 144, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 626, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 633, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 640, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 647, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 657, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 667, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 674, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 681, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 690, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 697, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 704, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 711, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 718, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 728, .adv_w = 144, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 734, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 742, .adv_w = 144, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 745, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 753, .adv_w = 144, .box_w = 8, .box_h = 3, .ofs_x = 0, .ofs_y = 7},
    {.bitmap_index = 756, .adv_w = 144, .box_w = 6, .box_h = 4, .ofs_x = 2, .ofs_y = 6},
    {.bitmap_index = 759, .adv_w = 208, .box_w = 12, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 779, .adv_w = 224, .box_w = 13, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 799, .adv_w = 176, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 806, .adv_w = 176, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
};


/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_1[] = {
    0x0, 0xef71, 0xefc1, 0xefc7, 0xefc8
};

/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 176, .range_length = 61385, .glyph_id_start = 96,
        .unicode_list = unicode_list_1, .glyph_id_ofs_list = NULL, .list_length = 5, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};


/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};


/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t fixed_9x15b = {
#else
lv_font_t fixed_9x15b = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 15,          /*The maximum line height required by the font*/
    .base_line = 3,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};



#endif /*#if FIXED_9X15B*/
